# configs/exp_baseline.yaml
# Baseline: 不使用 long-tail 策略
task: "detection"

# Data
image_dir: "data/CVPDL_hw2/train"
# test_image_dir: "data/CVPDL_hw2/test"
imgsz: 640
batch: 10
workers: 8

# Data Split (使用比例切分)
split_method: "ratio"
train_ratio: 0.8 # 假設 80% 訓練
val_ratio: 0.2   # 假設 20% 驗證
test_ratio: 0.0

# Model
model_name: "yolov8m.yaml"  # <--- 修改點：明確指定 .yaml (from scratch)
num_classes: 4
class_names: ["car", "motorcycle", "person", "hov"]

# Training
lr: 0.001
weight_decay: 0.0001
optimizer: "AdamW"

# Loss Hyperparameters (for v8DetectionLoss)
loss_hpy:
  box: 7.5      # box loss gain
  cls: 0.5      # cls loss gain
  dfl: 1.5      # dfl loss gain
  iou_type: 'ciou'  # (ciou, giou, diou)

# Long-tail (DISABLED for baseline)
use_cb_loss: false
use_repeat_factor_sampling: false
samples_per_cls: [23000, 5000, 3000, 1000] # (用於 Logit Adj. 但 baseline 沒開)

# Evaluation
conf_threshold: 0.001
iou_threshold: 0.6    # NMS 之前的 IoU (v8 似乎不用)
nms_iou: 0.7          # NMS 階段的 IoU